font_size 13.0
foreground #c6d0f5
background #232634
background_opacity 0.8
font_family      JetBrainsMono Nerd Font

# Nice spacing
adjust_line_height  110%
adjust_column_width 105%

# Tabs
tab_bar_style powerline
tab_powerline_style slanted

# Cursor + bell
cursor_shape block
enable_audio_bell no

# Scrollback
scrollback_lines 20000

# Make colors match apps properly
term xterm-kitty
